FROM alpine
MAINTAINER Vaccove Crana, LLC. <humans@vacco.io>

ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US:en
ENV LC_ALL=en_US.UTF-8
ENV ZULU_PACK=zulu11.70.15-ca-jre11.0.22-linux_musl_x64.tar.gz
ENV ZULU_DIR=zulu11.70.15-ca-jre11.0.22-linux_musl_x64
ENV INSTALL_DIR=/usr/lib/jvm
ENV BIN_DIR=/usr/bin
ENV MAN_DIR=/usr/share/man/man1
    
RUN apk --no-cache add ca-certificates libgcc libstdc++ ttf-dejavu wget
RUN wget -q https://cdn.azul.com/zulu/bin/${ZULU_PACK}
RUN mkdir -p ${INSTALL_DIR}

RUN tar -xf ./${ZULU_PACK} -C ${INSTALL_DIR} && rm -f ${ZULU_PACK} && \
    cd ${BIN_DIR} && \
    find ${INSTALL_DIR}/${ZULU_DIR}/bin -type f -perm -a=x -exec ln -s {} . \; && \
    mkdir -p ${MAN_DIR} && \
    cd ${MAN_DIR} && \
    find ${INSTALL_DIR}/${ZULU_DIR}/man/man1 -type f -name "*.1" -exec ln -s {} . \;

ENV JAVA_HOME=/usr/lib/jvm/${ZULU_DIR}
